
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shubham karmokar
 */
public class StudentsDetails extends javax.swing.JFrame {
    ArrayList arr=new ArrayList();
    ArrayList arr1=new ArrayList();
    /**
     * Creates new form StudentsRegistration
     */
    public StudentsDetails() {
        initComponents();
            
        arr.add("");
        arr.add("CS");
          arr.add("IT");
          arr.add("EXTC");
         arr.add("ETRX");   
           arr.add("MECH");
           for(Object ob:arr){
               cmbbranch.addItem(ob);
           }
           
           arr1.add("");
        arr1.add("sem1");
          arr1.add("sem2");
          arr1.add("sem3");
         arr1.add("sem4");   
           arr1.add("sem5");
           arr1.add("sem6");
           arr1.add("sem7");
           arr1.add("sem8");
           
           for(Object ob:arr1){
               cmbsem.addItem(ob);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtrollno = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cmbbranch = new javax.swing.JComboBox();
        cmbsem = new javax.swing.JComboBox();
        txtname = new javax.swing.JTextField();
        txtmidname = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Roll No:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 340, 63, 22);

        txtrollno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtrollno);
        txtrollno.setBounds(240, 340, 212, 28);

        btnsubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\SURYA\\Desktop\\Dashboard\\Untitled1.png")); // NOI18N
        btnsubmit.setText("submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit);
        btnsubmit.setBounds(600, 480, 240, 50);

        btnback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\SURYA\\Desktop\\Dashboard\\back.png")); // NOI18N
        btnback.setText("back");
        btnback.setMaximumSize(new java.awt.Dimension(300, 131));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(190, 490, 200, 40);

        cmbbranch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbbranch.setBorder(null);
        cmbbranch.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cmbbranch.setOpaque(false);
        cmbbranch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbranchItemStateChanged(evt);
            }
        });
        cmbbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbranchActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbranch);
        cmbbranch.setBounds(220, 240, 300, 21);

        cmbsem.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cmbsem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsemItemStateChanged(evt);
            }
        });
        cmbsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsemActionPerformed(evt);
            }
        });
        getContentPane().add(cmbsem);
        cmbsem.setBounds(240, 300, 280, 22);

        txtname.setOpaque(false);
        getContentPane().add(txtname);
        txtname.setBounds(150, 170, 180, 32);

        txtmidname.setOpaque(false);
        getContentPane().add(txtmidname);
        txtmidname.setBounds(349, 170, 170, 32);

        txtcontact.setOpaque(false);
        getContentPane().add(txtcontact);
        txtcontact.setBounds(740, 352, 240, 30);

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(22, 220, 0, 0);

        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(620, 120, 230, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\SURYA\\Desktop\\Dashboard\\signup main student.PNG")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1150, 630);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 126, 166, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String name=txtsurname.getText()+" "+txtname.getText()+" "+txtmidname.getText();
        String fname=txtrollno.getText();
        String contact=txtcontact.getText();
        String branch=String.valueOf(cmbbranch.getSelectedItem());
        String sem=String.valueOf(cmbsem.getSelectedItem());
        int rollno=Integer.parseInt(txtrollno.getText());
        System.out.println(branch);
        System.out.println(sem);
         try {
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/placement","root","Mysql@123");
           
          
            
            PreparedStatement ps=conn.prepareStatement("insert into academicdetails values(?,?,?,?,?)");
            ps.setString(1,name);
            ps.setString(2,txtrollno.getText());
            ps.setString(3,branch);
            ps.setString(4,sem);
            ps.setString(5,contact);
            
            int num=ps.executeUpdate();
            if(num>0){
                JOptionPane.showMessageDialog(rootPane, "Registered successfully");
                
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "not registered");
                
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        MainMenu mn=new MainMenu();
        mn.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnbackActionPerformed

    private void cmbbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbranchActionPerformed

    private void cmbbranchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbranchItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbranchItemStateChanged

    private void cmbsemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsemItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsemItemStateChanged

    private void cmbsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsemActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox cmbbranch;
    private javax.swing.JComboBox cmbsem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtmidname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtrollno;
    // End of variables declaration//GEN-END:variables
}
